### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by bigpyer** [aosabook/500lines#134]
Hi @ondras, thanks for your contributions, i face some difficulties.
1.where i can get the installation instructions.
2.when i run `python build.py --pdf`(the lib of requirements.txt is installed), i got "OSError: [Errno 2] No such file or directory",but the files is there
Thank yout!

**Comment by ondras** [comment]
Hi @bigpyer,

can you please provide some more context here? I am not sure what contributions are you talking about.

**Comment by bigpyer** [comment]
i just want the installation steps(generate pdf documents)
i run "python build.py --pdf" and errors like this:


python _build/preprocessor.py --output=tex/pedometer.markdown --markdown ./pedometer/pedometer.markdown

No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/envoy/core.py", line 214, in run
    out, err = cmd.run(data, timeout, kill_timeout, env, cwd)
  File "/usr/local/lib/python2.7/site-packages/envoy/core.py", line 93, in run
    raise self.exc
OSError: [Errno 2] No such file or directory

**Comment by ondras** [comment]
I see. Well, perhaps you might have confused me with somebody else, as I have no direct relation to this project; I have no knowledge about its build process and I never tried to build it.

**Comment by Chris-May** [comment]
I can confirm that the book doesn't build with `python build.py --pdf`. I got a host of `OSError: [Errno 2] No such file or directory` errors after downloading the repo and installing the dependencies in `requirements.txt` into a fresh virtualenv.

I've also tried several of the other format arguments, all with similar problems, though I did notice that an `epub` folder appeared after I tried that option.

I can't tell if there's another way one should generate the book.

I also can't tell if one is _supposed_ to be able to create the book.

From the issues list it sounds like this project should "launch" soon?

**Comment by MichaelDiBernardo** [comment]
I'll be writing up some instructions on how to get this running, but it probably won't be anytime soon (until after the print version has launched.) It has been a lot of spit and chewing gum up until this point; there are certain dependencies that are going to be problematic unless you know you need to have them.

Once the print version is ready, I'm going to make sure that people can at least build the PDF relatively easily on their own. But that won't be for a few months yet. For details of our early access release, watch our Twitter at https://twitter.com/aosabook -- we'll be announcing something today!

**Comment by ymant** [comment]
i also meet the problems.
Traceback (most recent call last):
  File "build\bdist.win32\egg\envoy\core.py", line 214, in run
    out, err = cmd.run(data, timeout, kill_timeout, env, cwd)
  File "build\bdist.win32\egg\envoy\core.py", line 93, in run
    raise self.exc
WindowsError: [Error 2]

bibtex 500L


Traceback (most recent call last):
  File "build\bdist.win32\egg\envoy\core.py", line 214, in run
    out, err = cmd.run(data, timeout, kill_timeout, env, cwd)
  File "build\bdist.win32\egg\envoy\core.py", line 93, in run
    raise self.exc
WindowsError: [Error 2]

pdflatex -interaction nonstopmode 500L


Traceback (most recent call last):
  File "build\bdist.win32\egg\envoy\core.py", line 214, in run
    out, err = cmd.run(data, timeout, kill_timeout, env, cwd)
  File "build\bdist.win32\egg\envoy\core.py", line 93, in run
    raise self.exc
WindowsError: [Error 2]

**Comment by damienvaz** [comment]
+1 ! Having problem ...

**Comment by techgaun** [comment]
@bigpyer @Chris-May (and hopefully helps others too). On Ubuntu, I installed the following stuffs:
```shell
sudo apt -y install texlive-full   # I already had this
sudo apt -y install pandoc   # this should get rid of OSError you're getting.
```

With just above installs, I have been able to run the build.py file to generate pdf. In case it does not work, just lmk and I'll try find the issue and its solution.

**Comment by eriknstr** [comment]
Cloned at commit b5ee54148551b2e71991cf0a4858d86b671f6e52 (Sun May 29 12:00:31 2016 -0400) using Fedora 23. I installed pandoc and the full texlive, then I installed the dependencies from `requirements.txt`.

```bash
sudo dnf install texlive-scheme-full pandoc
sudo pip2 install -r requirements.txt
```

I ran `python2 ./build.py --pdf`. [Log attached](https://github.com/aosabook/500lines/files/288428/pdf_log.txt). I got a few errors and warnings, but it did produce a PDF with what appears to be the complete contents, though no front page. [PDF attached for reference](https://github.com/aosabook/500lines/files/288427/500L_pdf.zip).

Next, I tried `python2 ./build.py --epub`. [Log attached](https://github.com/aosabook/500lines/files/288430/epub_log.txt). This failed due to not finding a file named `image-list.txt`. No ePub file was produced and the PDF that was previously built has now been deleted.

After that, I tried `python2 ./build.py --pandoc-epub`. [Log attached](https://github.com/aosabook/500lines/files/288431/pandoc_epub_log.txt). No ePub file was produced.

Next, I tried `python2 ./build.py --epub --pandoc-epub`. [Log attached](https://github.com/aosabook/500lines/files/288432/epub_pandoc_epub_log.txt). Like with `python2 ./build.py --epub`, this fails due to not finding the `image-list.txt` file.

Finally, I tried `python2 ./build.py --html`. Log attached as `html_log.txt`. This results in *some* output under `html/output/`, but only five of the files are HTML files and most of these are empty. The output is too big to attach on GitHub but [here's a tree view of `html/output/`](https://github.com/aosabook/500lines/files/288433/tree_html_output.txt).

**Comment by char101** [comment]
To build the epub, first create the nonexistent files

```
touch epub/epubtitle.txt epub/introduction.markdown epub/image-list.txt
```

then run

```
python build.py --epub --pandoc-epub
```

The zip command will fail but the epub will be created and readable otherwise. The images in the epub is too large though.

**Comment by char101** [comment]
To build the pdf with bookmarks, first build the pdf as usual, then chdir to `pdf/`, edit 500L.tex replacing 

`% \usepackage{hyperref}` with `\usepackage[bookmarks]{hyperref}`

and 

`\setcounter{tocdepth}{0}` with `%\setcounter{tocdepth}{0}`.

**Comment by MichaelDiBernardo** [comment]
I've added build instructions in f0e5a10e6605ed5c0fbeab8a2b40b8805b501960. Thanks to all here who helped out in the interim before I could get to this.

**Comment by allonhadaya** [comment]
I also experienced this issue on Ubuntu 14.04.

For me, this issue had to do with `pdflatex -interaction nonstopmode 500L` failing. Perhaps the build script could be improved to stop in case of command failure rather than continuing to trying to move the non-existent pdf to `output/`.

The fix for me was to install pdflatex as illustrated in this gist: https://gist.github.com/rain1024/98dd5e2c6c8c28f9ea9d
