### ISSUE TITLE
Control flow diagram not showing up for ci project

### ISSUE THREAD

**Issue by Deborah-Digges** [aosabook/500lines#178]
At this link: http://aosabook.org/en/500L/pages/a-continuous-integration-system.html#figure-12.1,
the control flow diagram is not showing up.

Update: I think images for all the lessons can't be found

**Comment by MichaelDiBernardo** [comment]
Hi,

Where did you find this link? This is an artefact of our (currently somewhat shoddy) build process. The chapter pages are copied both to en/500L/ and en/500L/pages, but internal chapter resource URLs are generated so that only the former will work.

If you go to http://aosabook.org/en/500L/blockcode-a-visual-programming-toolkit.html (which is what we linked from the blogposts etc.), that will work. So now I'm worried we linked to the wrong location elsewhere :)
