### ISSUE TITLE
some image maybe 404

### ISSUE THREAD

**Issue by AbyChan** [aosabook/500lines#181]
I love 500lines articles, but some image load fail. please check.
like this link [http://aosabook.org/en/500L/pages/blockcode-a-visual-programming-toolkit.html](http://aosabook.org/en/500L/pages/blockcode-a-visual-programming-toolkit.html)

**Comment by NamPNQ** [comment]
Confirm

**Comment by MichaelDiBernardo** [comment]
Hi,

Where did you find this link? This is an artefact of our (currently somewhat shoddy) build process. The chapter pages are copied both to  `en/500L/` and `en/500L/pages`, but internal chapter resource URLs are generated so that only the former will work. 

If you go to http://aosabook.org/en/500L/blockcode-a-visual-programming-toolkit.html (which is what we linked from the blogposts etc.), that will work. So now I'm worried we linked to the wrong location elsewhere :)

**Comment by AbyChan** [comment]
got it

**Comment by courthead** [comment]
@MichaelDiBernardo Just an FYI that [this page](http://aosabook.org/en/500L/) links to the chapters with the `en/500L/pages` prefix. It's the 5th result for the Google search "500 lines or less". It does have a message saying that "If you're here, you're in the wrong place", but my guess is that most people will ignore that message because:

- it doesn't give [a reason why](http://rayedwards.com/always-give-a-reason-why/) it's the wrong place
- the links on the page seem to work just fine
- a list of chapter links is a much more convenient UI than the blog

Hope this helps!

**Comment by MichaelDiBernardo** [comment]
Thanks @courthead :) The AOSA site will be undergoing a restructure very shortly to prepare for the 500Lines launch, so I will defer this until then.
