### ISSUE TITLE
Test print issues

### ISSUE THREAD

**Issue by MichaelDiBernardo** [aosabook/500lines#228]
I've received the test print and given it a first scan. Here are the issues I've found:

- [x] Introduction: "subdirectory of project folder" -> "subdirectory of each project folder"
- [x] Introduction: Leah Hanson's italics have a bare "emph" in the beginning
- [x] Blockcode: Spare ')' at the end of "important vehicles for learning"
- [x] CI: control clow diagram "below is overview diagram of this system", missing "of"
- [x] Cluster: 'class Scout' got orphaned on bottom of p.46
- [x] Cluster: pp.52 class Timer doesn't really seem like it needs to be punted all the way to the facing page
- [x] Cluster: "Paxos Made Practical" reference in References section should be an href, not a footnote
- [x] Dagoba: "Method chaining lets us write" footnote got cut off after "instead of:"
- [x] Image filter: pp.238 bottom: "Notice that:" is by itself bottom of page
- [x] Modeller: pp.272 one line of code made it under the big image
- [x] Object model: pp.292/293 huge whitespace before codeblock
- [x] SOP: pp.350 bad quotes on "*.mit.edu"

I'm going to fix these now.

cc: @amyrbrown

**Comment by amyrbrown** [comment]
I found a [few things](https://www.instagram.com/p/BG-YwOeRCAk/): 

- [ ] There are a few right-hand pages which are missing their footer (author's name) — it's always the last right-hand page of the chapter, so I don't know if there is some wacky LaTeX logic at play here. The affected pages are: 15 (Elza), 31 (Das), 81 (Rhodes & Rocco), 189 (Muise), 213 (Rubin), 289 (Dransch), 307 (Bolz), 373 (Kang et al), 393 (Hamrick), 429 (Hanson)
- [ ] Resolution on the title and editor name on title pages is not great — I will remake the images
- [ ] Copyright page: Second line should read "Edited by Michael DiBernardo"
- [ ] Copyright page: Let's put `http://` in front of my URL and style it as code to be consistent with the other URLs on the page
- [ ] Copyright page: ISBN doesn't match the one on the barcode on the cover — I think the barcode one is correct, but let me know if it isn't and I'll fix it.
- [ ] Contents: I wonder if we should remove "Dr." from the author's name for chapter 9 — no-one else has titles and it looks a bit weird. Should run it by the author first if possible.
- [ ] p vii: Single quotes around "open source applications" where we have used double quotes elsewhere in the book
- [ ] p viii: Second last line, no capital on "graphic designer"
- [ ] p 55 (Clustering): lots of whitespace at the bottom of this page too — something weird about this chapter?
- [ ] p 75, 78 (Contingent): whitespace at the bottom of the page — would it be better to break up the code on the following pages? (There goes my Clustering-chapter theory.)
- [ ] p 92 (Web Crawler): Figure 5.1 shows up between a sentence ending with a colon and the code it introduces on the next page — can we move the figure?
- [ ] p 109 (Dagoba): noindent on the first paragraph (after the quotes)
- [ ] p 109 (Dagoba): first footnote marker should not have a space before it. (Possibly worth grepping for that generally because I found a couple more.)
- More generally I wish we had decided to always have footnote markers outside the punctuation, because we're inconsistent now, but I think it's too late to change that.
- [ ] p 119 (Dagoba): More big whitespace at the bottom of the page. I can kind of see what LaTeX is thinking here but I wonder if the header and first para of the next section would fit...?
- [ ] p 121 (Dagoba): Footnote marker #20 actually ended up on the next line here.
- [ ] p 194 (Database): noindent at "And here's" (because it's a logical continuation of the paragraph which started above the code).
- [ ] p 299 (Object Model): biggish whitespace here — I'm not sure why LaTeX sometimes breaks up code and sometimes doesn't.
- [ ] p 321 (OCR): It's University of Willamette, not Williamette (text is wrong, footnote URL is correct).
- [ ] p 331 (Pedometer): noindent at "In accounting for" because it's the first paragraph after the header.
- [ ] p 372 (Same-origin): Space before footnote 3.
- [ ] p 378 (Sampler): Text of header should be "Descriptive versus Mathematic", not "Descriptive vs. Mathematic"
- [ ] p 407, 408 (Spreadsheet): spaces around em-dash — everywhere else in the book we have no spaces around em-dash. (Probably worth a search-and-replace.)
- [ ] p 434 (Template Engine): There's a list in the paragraph which starts "Rendering the template" which should be either formatted as an actual list, or rewritten to be a sentence (with semi-colons between the items).
- [ ] p 442 (Template Engine): noindent on the two "paragraphs" starting with "which" (because they're actually just continuations of the sentence started before the code).
- [ ] p 446 (Template Engine): noindent on "or can be a complex..."
- [ ] p 445 (Web Server): noindent on "and the method..."
- [ ] p 459 (Web Server): noindent on "and here's how..."
- [ ] p 464 (Web Server): noindent on "while the parent..." and "and the handler..."
- [ ] p 465 (Colophon): I Googled and it looks like the common terminology is actually "focus-stacked", so "is composed of 23 separate focus-stacked images". I would also write out "23" as "twenty-three".

Sorry. :)

**Comment by MichaelDiBernardo** [comment]
Cool! I should be able to address all of these over the weekend. Thanks @amyrbrown!

**Comment by MichaelDiBernardo** [comment]
Own notes as I go:
- [ ] New images look better but result in bottom of "by" being cut off a bit

**Comment by MichaelDiBernardo** [comment]
Hi @amyrbrown,

I fixed all but two of the discussed issues. I'll address those, and add one of my own here:

> There are a few right-hand pages which are missing their footer (author's name)

This seems "intentional" for some definition of template/LaTeX-intentional -- I'm fine leaving it as-is if you are?

> I wonder if we should remove "Dr." from the author's name for chapter 9

The contributor in question previously asked to have the "Dr." attribution included, so for that reason I think we should leave it in.

I have one last thing. It seems like the new version of [eds.pdf](https://github.com/aosabook/500lines/blob/master/minutiae/frontmatter-images/eds.pdf) has a vertically truncated 'y' character. Could I bug you to regenerate this one without the clipping?

Thanks so much for this list!!

**Comment by amyrbrown** [comment]
The footers kind of bug me but no-one else will notice (until they read this thread LOL!) – I say leave it because the headache of fixing it will probably be wildly disproportionate.

I'm fine with leaving the "Dr." in.

Ack, sorry the eds.pdf file is truncated. I'll try and get a new version to you tonight — if not, tomorrow.

**Comment by MichaelDiBernardo** [comment]
Yay :)

**Comment by amyrbrown** [comment]
\o/ :D
